### ISSUE TITLE
Liste des demandes d avis - interface DSFR

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#350]
Développer l'interface DSFR permettant de réaliser les actions de l'issue: https://github.com/datalab-mi/Basegun/issues/349#issue-2138824711
# Tasks
Afficher une demande par ligne avec :

- [ ]  La date et l'heure d'envoi de la demande
- [ ]  l'identifiant de la demande
- [ ]  le statut de la demande
- [ ]  l'agent en charge de la demande (à qui on l'a attribué)
- [ ]  la date de dernière modification (enregistrement de la demande OU date de traitement OU date de refus )
- [ ]  un bouton permettant d'ouvrir la demande

**Comment by leihuayi** [comment]
Au final pas besoin d'un backend de gestion d'utilisateurs et de demandes, envoi direct des demandes par mail (voir https://github.com/dnum-mi/basegun/milestone/3)
