### ISSUE TITLE
Repondre a une demande

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#351]
Description des fonctionnalités liées à la constitution d'une réponse à une demande d'avis : 
L'expert ouvre une demande d'avis et interagit avec cette demande en attribuant celle-ci à un expert qui la traitera.
Les experts attribuent une catégorie légale et peuvent rédiger un commentaire pour apporter des informations complémentaires.

# Tasks
Afficher en entête :
- [ ] Le N° de la demande
- [ ] Le statut de la demande
- [ ] La date et l'heure de la demande
- [ ] Via un menu déroulant "attribuer" : permettre l'attribution de la demande à un agent de la permanence (repris de la liste des utilisateurs de la permanence). => _notion de groupe_
- [ ] L'agent en charge de la demande. **IMPORTANT** : si un agent a été attribué grâce au menu déroulant, le champ ne doit pas être verrouillé pour permettre la réattribution de la demande à un autre agent (tous les agents doivent pouvoir attribuer)

Afficher ensuite sous le titre "**Informations de la demande**", les éléments suivants :
- [ ] l'identifiant du demandeur NIGEND (GN) / MATRICULE (PN) - reprendre l'entité d'appartenance 
- [ ] Mail, _renseigné dans le formulaire_
- [ ] Tel pro, _renseigné dans le formulaire_
- [ ] Service d'affectation, _renseigné dans le formulaire_
- [ ] Typologie de l'arme, _renseigné dans le formulaire_
- [ ] Précisions sur les marquages, _renseigné dans le formulaire_
- [ ] Toutes les photos ajoutées avec leur libellé : vue gauche, droite, etc... _renseigné dans le formulaire_
- [ ] Pouvoir zoomer sur les photos (via un bouton de zoom comme sur la mise en sécurité)

Afficher ensuite sous le titre "**Réponse à la demande d'identification**" :	
- [ ] Un champ de saisie libre "**Commentaire**" : l'expert y inscrira les éléments de réponse liés à la demande ou bien sa demande de compléments d'information dont il a besoin pour apporter une réponse.
- [ ] Le champ commentaire doit être obligatoirement rempli pour : **envoyer une réponse**, ou pour **demander des compléments d'information**
- [ ] Le champ commentaire n'est pas obligatoire pour (classer) une demande (non recevable) quand l'expert clique sur "**Demande non justifiée**"
- [ ] Une rubrique "**catégorie légale de l'arme** avec 6 boutons (choix unique) et les libellés "A1", "A2", "B", "C", "D", "Non classé". => Info obligatoire pour pouvoir "envoyer la réponse".
- [ ] Un bouton "Sauvegarder" : qui permet d'enregistrer son brouillon (sauvegarde du contenu du champ "commentaire" et de la catégorie légale éventuellement choisie) => _bascule la réponse au statut "En cours"_
- [ ] Un bouton "Envoyer la demande" : qui permet de déclencher la prévisualisation de la réponse qui va être envoyé au demandeur (SI le champ "commentaire" est complété ET SI la catégorie légale est renseignée). => bascule au statut "traité"
- [ ] Pour envoyer une demande d'informations complémentaires l'expert clique sur le bouton "demande d'informations complémentaires" (si les éléments transmis ne suffisent pas pour rédiger une réponse, l'expert complète le champ "commentaire" pour préciser les infos complémentaires à transmettre par le demandeur).
- [ ] Si la demande n'est pas légitime (photo non adaptée / abus de la fonctionnalité) : l'expert appui sur le bouton "Demande non justifiée" et classe sans suite la demande.
- [ ] Prévoir un bouton en fin de page pour que l'expert puisse revenir à la liste des demandes avec le bouton
