### ISSUE TITLE
Pouvoir previsualiser une reponse avant envoi

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#358]
L'idée est de permettre aux experts de prévisualiser tout envoi de message aux demandeurs

# Tasks

Après avoir cliqué sur "Envoyer la réponse" _(si tous les champs obligatoires sont complétés)_ l'expert arrive sur un écran de prévisualisation de la réponse qu'il va envoyer.
- [ ] Implémenter l'écran de prévisualisation faisant suite à "Envoyer la réponse" : 
1. Titre "Réponse à votre demande d'identification n° [N° de la demande]"
2. Rubrique "Commentaires" reprennant la réponse de l'expert 
3. Rubrique "La catégorie légale de l'arme prise en photo est " : _[Catégorie légale de l'arme renseignée]_
4. Afficher en fin de message : le texte de disclaimer d'Antoine Museau : _"Cet avis n'emporte qu'une simple valeur de renseignement, destiné à orienter votre enquête. Pour faire référence dans une procédure, cet avis doit impérativement et réglementairement être validé par le biais d'un examen scientifique ou technique prévu par le code de procédure pénale. Il vous appartient de solliciter, avec l'accord du procureur de la République, l'IRCGN ou un autre laboratoire par la voie de la réquisition judiciaire. La proposition de classification ci-après est donnée à titre indicatif, se basant uniquement sur les caractéristiques observables"_.

Après avoir cliqué sur "Demander plus d'informations"_(si tous les champs obligatoires sont complétés)_ l'expert arrive sur un écran de prévisualisation de la demande d'informations qu'il va envoyer.
- [ ] Implémenter l'écran de prévisualisation faisant suite à "Demander plus d'informations" : 
1. Titre "Demande d'identification n° [N° de la demande]"
2. Texte : "Afin de pouvoir identifier précisément l'arme envoyée dans votre demande, nous avons besoin d'informations complémentaires listées ci-dessous :"
3. Rubrique "Commentaires" reprenant la réponse de l'expert listant les éléments complémentaires à transmettre à l'expert par le demandeur.
4. Texte : "Merci de bien vouloir nous transmettre ces éléments pour que nous puissions vous apporter une réponse quant à l'identification de l'arme et de sa catégorie légale."
- [ ] En bas de la page de prévisualisation le bouton "Confirmer l'envoi" pour envoi de la réponse au [mail du demandeur]

**Comment by leihuayi** [comment]
Au final pas besoin d'un backend de gestion d'utilisateurs et de demandes, envoi direct des demandes par mail (voir https://github.com/dnum-mi/basegun/milestone/3)
