### ISSUE TITLE
Gestion des comptes utilisateurs

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#374]
Via un lien "Se créer un compte" , les utilisateurs (experts) peuvent préparer la création de leur compte et envoyer une demande d'activation de leur compte à un admin de leur permanence.
**_OU BIEN_**
Un administrateur peut directement créer un compte utilisateur pour un expert de sa permanence (première population du groupe d'experts par exemple).

# Tasks

### Auto création de compte
Sur la page de connexion, après avoir cliqué sur le bouton "Se créer un compte", l'agent accède à un formulaire (format DSFR) dans lequel il dispose de champs pour : 
- [x] Saisir son nom
- [x] Saisir son prénom
- [x] Saisir son mail pro (interieur.gouv.fr)
- [x] Saisir son tel pro
- [x] Pouvoir préciser s'il est de la police ou de la gendarmerie via deux bouton
- [x] Quand il choisit "Gendarmerie" : cela renseigne directement IRCGN comme entité de rattachement
- [x] Quand il choisit "Police" : 5 cases à cocher (choix unique) lui sont proposées : PTS Lille, PTS Lyon, PTS Paris, PTS Marseille, PTS Toulouse
![image](https://github.com/datalab-mi/Basegun/assets/150133063/ed4c77bb-fd41-42cc-ac9d-e2b53264c4af)
- [x] Un bouton pour envoyer sa demande
- [ ] L'envoi de cette demande génère un mail de demande de création de compte sur la boîte mail du LPS choisi (PN) ou de l'IRCGN avec les infos de l'utilisateur  **Blocked by mise en place du backend**

### Gestion des utilisateurs
- [ ] Réception d'une demande de création de compte par mail sur la BAL de l'admin et de la BAL fonctionnelle de la permanence, suite à la complétude du parcours "se créer un compte"
- [ ] Via un bouton "Gestion des utilisateurs", l'admin d'une permanence accède à la liste des utilisateurs de sa permanence comme au format de la liste des demandes
- [x] Il peut filtrer par nom
- [x] Il peut filtrer par statut (**actif / inactif / à créer**)
- [ ] Liste par nom / prénom, statut, date de dernière connexion, bouton pour modifier en bout de ligne.
![image](https://github.com/datalab-mi/Basegun/assets/150133063/58f461de-9446-41c7-8811-0b3bb6b7436b)
Un compte inactif est un compte qui ne peut plus accéder à l'espace de gestion des demandes
Un compte "à créer" est un compte à valider par un admin si l'expert à préparé la création de son compte, le super admin validera ensuite la création du compte via l'interface de gestion de compte en accédant à la fiche utilisateur.
![image](https://github.com/datalab-mi/Basegun/assets/150133063/cb74b9c1-c8c1-4d50-8848-b1f5aa6e1ad3)

**Comment by ClemGerard** [comment]
Ne pas intégrer le bouton réinitialiser le mot de passe dans la fiche d'un compte (cf. dernière capture).

**Comment by ClemGerard** [comment]
Travaux en pause en attendant les entrants sur Passage 2

**Comment by leihuayi** [comment]
Au final pas besoin d'un backend de gestion d'utilisateurs et de demandes, envoi direct des demandes par mail
