### ISSUE TITLE
Implement disclaimer behavior for shoulder weapons

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#441]
En fonction du type d'arme, de la présence d'une carte ou non, il est nécessaire d'adapter l'affichage des résultats finaux à l'écran.
Ci dessous sont listé les différents comportements attendus en fonction des cas (type d'arme et présence de carte ou non).

# Tasks
- [x] ![image](https://github.com/datalab-mi/Basegun/assets/150133063/17e426dc-d17b-46b9-8d78-a9c4c77a8d0b)
- [x] ![image](https://github.com/datalab-mi/Basegun/assets/150133063/21ef0248-e5b3-475f-9cb1-4946ba1addcf)
- [x] ![image](https://github.com/datalab-mi/Basegun/assets/150133063/9b3cf4ee-325e-4921-9640-40e61201b1a7)
- [x] ![image](https://github.com/datalab-mi/Basegun/assets/150133063/23e66578-4031-46d3-877b-d7c25370d8fe)
- [x] ![image](https://github.com/datalab-mi/Basegun/assets/150133063/19ba87fd-00a8-46a4-a61c-26cf84b5ec29)

- [x] Quand l'utilisateur sélectionne le parcours de mise en sécurité, S'IL N'A PAS MIS DE CARTE SUR LA PHOTO, on ne lui affiche pas l'écran d'alerte sur l'absence de photo (ecran card is missing). **MAIS S'IL SELECTIONNE "JE SOUHAITE IDENTIFIER MON ARME"** à la fin du parcours, alors l'écran d'alerte sur l'absence de carte s'affiche.

**Comment by ClemGerard** [comment]
soucis sur la typologie "ARME D'EPAULE A VERROU", dans le cas d'une photo SANS CARTE, le parcours se déroule correctement (enchaînement des écran), MAIS l'écran de résultat final comporte le mauvais disclaimer sur la typologie : n'afficher QUE les informations sur le nombre de munitions et non pas les types de canon. => reprendre le disclaimer de la typologie "arme d'épaule à levier de sous garde" sans carte.
