### ISSUE TITLE
Integrate data from Passage 2 in forms

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#469]
Depends on #402 

Assurer la reprise des informations récupérées via Passage 2 dans les formulaire de demande d'avis

##Tasks
Finaliser la mise en forme du formulaire pour gérer les données issues de Passage 2 (champs modifiables ou non) : 
- [x] Ecran INFO SUR LE DEMANDEUR
- Nom : non modifiable et obligatoire
- Prénom : Non modifiable et obligatoire
- Cas GN : NIGEND non modifiable et obligatoire
- Cas PN : RIO ou Matricule (modifiable et obligatoire)
- Service d'affectation : modifiable et non obligatoire
- N° de téléphone : non modifiable et obligatoire
- Adresse email : non modifiable et obligatoire 

- [x] Ecran INFORMATIONS SUR L'ARME
- N° UNA ou de procédure : modifiable et obligatoire

- [x] Faire correspondre les labels des variables de données avec les bons champs mentionnés ci-dessus.
- [x] Depends on #497 : afficher le formulaire uniquement après s'être loggé dans Passage2
      Détail:
     - [x] si la personne qui s'est authentifié est non gendarme (auth_idp != proxyma) alors rediriger vers une page/modale "Basegun ne fournit pas de moyen pour contacter les experts relatifs à votre service. Nous vous recommandons de suivre votre procédure de contact habituelle."
     - [x] sinon, on arrive à la page situation urgente / non urgente. Editer pour enlever "consignes envoi de mail"
     - [x] quand on clique sur situation non urgente, redirection vers formulaire
- [x] Vérifier que les données de Passage 2 (dans le token) remontent dans le formulaire, dans les bons champs

**Comment by leihuayi** [comment]
Variables:
- uid (-> remove prefix "3" to get nigend)
- last_name
- first_name
- email
- police_matricule
- service
- phone_number
- auth_idp (proxyma, cheops, passage2)

**Comment by ClemGerard** [comment]
- **Si gendarme : NIGEND = UID - "3"   => non modifiable**

- **Si police : police_matricule => si on a une valeur alors non modifiable, sinon champ modifiable.**

- MEttre en place un check par le back : si infos présentes, issue de passage 2, alors on garde les infos du back, si pas d'info ou info manquante, on récupère les infos du front pour le/les champs concernés.

**Comment by leihuayi** [comment]
Création d'un fichier de conf Keycloak pour simuler deux users "gendarmerie" et "police" avec leurs attributs de Passage2 (TODO @nutfdt ) qui permet de tester les deux parcours différents selon quel type d'user s'authentifie

**Comment by leihuayi** [comment]
Ca fonctionne avec Keycloak mais on ne sait pas encore pour passage2

**Comment by nutfdt** [comment]
Etape 1

![Etape 1](https://github.com/user-attachments/assets/facffb8e-84e9-42f9-b13d-ea5ae103bbac)
Etape 2

![Etape 2](https://github.com/user-attachments/assets/97434e32-0c1d-4658-b5ae-0eac9e9a2169)
Etape 3

![Etape 3](https://github.com/user-attachments/assets/14909a43-c111-4dac-bc2f-21846d615b5d)

**Comment by leihuayi** [comment]
Problème de redirection après auth sur Passage2

**Comment by leihuayi** [comment]
Problème de redirection, changement de l'url autorisée après login dans auth /auth/callback. Actuellement encore problème de page blanche
Problème pour déployer via DSO à cause de pull rate limite du compte DSO sur Docker Hub. Bloqués...
A tester en qualif

**Comment by thomashbrnrd** [comment]
Problèmes vus avec Antoine M :
- Problème lors de la première connexion, l’utilisateur n’est pas correctement redirigé.
- Description des marquages pas clair ? A voir comment améliorer.
- “Vu rapprochée marquage” ne devrait pas être obligatoire.
