### ISSUE TITLE
Create endpoint Demande d avis

### ISSUE THREAD

**Issue by ClemGerard** [dnum-mi/basegun#498]
Depends on #402 

# Tasks

- [ ] Vérification du token par le backend
- [ ] Créer l'endpoint "Demande d'avis" avec envoi de mail
- [ ] Créer un log pour tracer l'envoi d'une demande d'avis
